REV = d1a98fe
PKG = alog
SRC = https://git.codelabs.ch/git/alog.git

BUILD_OPTS = LIBRARY_KIND=static

INSTALL_OPTS = $(BUILD_OPTS) PREFIX=$(BUILDDIR)

all: install_default

include ../contrib.git.mk
