REV = bd0ed91cb985a697033edd9fd62d322aa017e791
PKG = libhwbase
SRC = https://review.coreboot.org/libhwbase.git

PATCHES = \
	0001-mutime-Make-Sinfo-an-imported-constant.patch \
	0002-static_mmio-Disable-SPARK-for-Set_Base_Address-body.patch \
	0003-time-Add-T_First-constant.patch

include ../contrib.git.mk
