REV = cf01ab6e40ce7229cf6740fe1b7e0e107b396a23
PKG = libhwbase
SRC = https://review.coreboot.org/libhwbase.git

PATCHES = \
	0001-mutime-Make-Sinfo-an-imported-constant.patch \
	0001-static_mmio-Disable-SPARK-for-Set_Base_Address-body.patch

include ../contrib.git.mk
