#!/bin/bash

if [ ! $# -eq 3 ]; then
	echo "Usage: $0 <config_file> <commit> <build ID>"
	exit 1
fi

CONFIG=$1
COMMIT=$2
BUILDID=$3

if [ ! -f $CONFIG ]; then
	echo "Unable to read config file '$CONFIG'"
	exit 1
fi

config_header=$(head -n 1 $CONFIG)

if [ "$config_header" != "### muen_integ_config ###" ]; then
	echo "Invalid config file '$CONFIG'"
	exit 1
fi

source $CONFIG

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKDIR=$SCRIPTDIR/../..

HARBOR="Harbormaster build http://muen-builder.codelabs.local/B$BUILDID"
SAVE_ARTIFACTS=0

# servers to kill on exit
KILL_ON_EXIT_PIDS=()

export PATH=/usr/lib/ccache:/opt/gnat/bin:/opt/spark/bin:$PATH
export DISPLAY=:0
export CC="ccache gcc"

export AMT_PASSWORD=$AMT_PASSWORD

trap cleanup EXIT

acquire_file_lock()
{
	while [ -f $LOCK ]; do
		log "$0 already running with PID `cat $LOCK`, waiting ..."
		sleep 10
	done

	echo $$ > $LOCK
}

release_file_lock()
{
	if [ `cat $LOCK` -eq $$ ]; then
		rm -f $LOCK
	fi
}

cleanup()
{
	for pid in ${KILL_ON_EXIT_PIDS[@]}; do
		log "Killing server process with PID $pid"
		kill -kill $pid >>$LOGFILE 2>&1 || true
	done

	release_file_lock
}

log()
{
	echo $1 | tee -a $LOGFILE
}

send_mail()
{
	status=$1
	message=$2

	for mail in $RECIPIENTS
	do
		echo -e "To: $mail\nFrom: $SENDER\nSubject: [muen-integration] $status: B$BUILDID, $FBRANCH, $COMMIT\n\n$message" | /usr/sbin/sendmail -t -F "$SENDER" -f "$SENDER"
	done
}

check_if_head()
{
	remotes=`git branch -r --contains $COMMIT`
	for remote in $remotes
	do
		head=`git rev-parse $remote`
		if [ "$COMMIT" = "$head" ]; then
			log "Commit $COMMIT is HEAD of $remote branch"
			FBRANCH=$remote
			return
		fi
	done

	log "Commit $COMMIT is not a branch HEAD, skipping build"
	exit 1
}

save_artifacts()
{
	cp $WORKDIR/emulate/bochsout.txt $LOGDIR >>$LOGFILE 2>&1
	cp $WORKDIR/emulate/emulate.out $LOGDIR >>$LOGFILE 2>&1
	cp $WORKDIR/emulate/serial.out $LOGDIR >>$LOGFILE 2>&1
}

passed()
{
	log "State -> PASSED"
	send_mail PASSED "Integration test successful for:\n\n$GITLOG\n\n$HARBOR"
}

failed()
{
	log "State -> FAILED"
	send_mail FAILED "Integration test failed for:\n\n$GITLOG\n\nLog:\n`tail -n 50 $LOGFILE`"
	if [ $SAVE_ARTIFACTS -ne 0 ]; then
		save_artifacts
	fi
	exit 1
}

execute()
{
	cmd=$1
	log "Executing command '$cmd'"
	$cmd >> $LOGFILE 2>&1
	status=$?
	if [ $status -ne 0 ]; then
		log "! Command '$cmd' failed (status $status)"
		failed
	fi
}

expect()
{
	file=$1
	pattern=$2
	log "Expect pattern '$pattern' in file '$file'"
	grep "$pattern" $file >>$LOGFILE 2>&1
	if [ $? -ne 0 ]; then
		log "Expected pattern '$pattern' not found in '$file'"
		failed
	fi
}

bochs_emulate()
{
	SAVE_ARTIFACTS=1
	execute "make emulate"
	execute "sleep $BOOTWAIT_BOCHS"
	save_artifacts
	SAVE_ARTIFACTS=0

	expect $LOGDIR/serial.out "Booting Muen kernel"
	expect $LOGDIR/serial.out "Welcome to Linux on Muen SK"

	expect $LOGDIR/bochsout.txt "CPU 1 started up at 0000:00000000 by APIC"
	expect $LOGDIR/bochsout.txt "CPU 2 started up at 0000:00000000 by APIC"
	expect $LOGDIR/bochsout.txt "CPU 3 started up at 0000:00000000 by APIC"

	execute "make -C emulate clean"
}

hw_deploy()
{
	hardware=$1
	target_ip=$2

	execute "ping -c 6 $target_ip"
	xterm -e script -f -c "amtterm $target_ip" $LOGDIR/amt.out &
	pid_xterm=$!
	log "xterm pid is $pid_xterm"

	execute "make deploy HARDWARE=$hardware SYSTEM=integration_tests"

	cd $ROOT; python -m SimpleHTTPServer 10000 >$LOGDIR/http.out 2>&1 &
	pid_http=$!
	log "SimpleHTTPServer pid is $pid_http"
	cd $WORKDIR

	execute "sleep $HW_BOOTWAIT"

	kill $pid_xterm >>$LOGFILE 2>&1
	if [ $? -ne 0 ]; then
		log "Stopping AMT console failed, retrying on exit"
		KILL_ON_EXIT_PIDS+=($pid_xterm)
	fi
	kill $pid_http >>$LOGFILE 2>&1
	if [ $? -ne 0 ]; then
		log "Stopping HTTP server failed, retrying on exit"
		KILL_ON_EXIT_PIDS+=($pid_http)
	fi

	echo y | amttool $target_ip powerdown >>$LOGFILE 2>&1
	execute "make -C deploy clean"

	expect $LOGDIR/amt.out "Booting Muen kernel"
	expect $LOGDIR/amt.out "Routing IRQ 01 as vector 21 to CPU 00 with APIC ID 00"
	expect $LOGDIR/amt.out "Routing IRQ 14 as vector 34 to CPU 01 with APIC ID 01"
	expect $LOGDIR/amt.out "Routing IRQ 10 as vector 30 to CPU 03 with APIC ID 03"
	expect $LOGDIR/amt.out "VT-d DMA address translation enabled for IOMMU 01"
	expect $LOGDIR/amt.out "VT-d DMA address translation enabled for IOMMU 02"
	expect $LOGDIR/amt.out "Console output round 100"
	expect $LOGDIR/amt.out "100%"
	expect $LOGDIR/amt.out "stresstest DONE"
	expect $LOGDIR/amt.out "integtest DONE"

	expect $LOGDIR/http.out "200"
}

workdir_clean()
{
	execute "git remote prune origin"
	execute "make distclean"
	execute "cd components/linux/src"
	execute "git clean -dxf"
	execute "cd $WORKDIR"
}

mkdir -p $LOGDIR

log "Muen integration test starting for commit $COMMIT"
log "$HARBOR"
echo "Logging to file $LOGFILE"

acquire_file_lock

execute "cd $WORKDIR"
execute "git fetch"

if [ $CHECK_HEAD -eq 1 ]; then
	check_if_head
fi

execute "git checkout $COMMIT"

if [ $DO_CLEAN_WORKDIR -eq 1 ]; then
	workdir_clean
fi

GITLOG=`git log -1`
execute "git submodule update"

bochs_emulate
hw_deploy $HARDWARE $TARGET_IP

passed
