COMPONENT = muinit

COMP_HAS_BIN =

NO_PROOF = 1

# Required because unused subprogram LSC.AES.Print.Print_Round has dynamic
# stack, see also T578.
STACK_OPTS = --allow-dynamic

include ../component_spark.mk
