REV = SPARK2014
PKG = libsparkcrypto
SRC = https://git.codelabs.ch/git/spark-crypto.git

PATCHES = \
	0001-Specify-object-size-of-SHA256-types.patch \
	0002-Fix-explicit-membership-test-compiler-warning.patch \
	0003-Make-array-types-packed.patch

include ../contrib.git.mk
