include ../../Makeconf

BUILD_OPTS += --RTS=$(TOP_DIR)/rts/obj

ifdef GENERATE_CSPECS_FROM
COMPONENT_TARGETS += cspecs
endif

$(COMPONENT): $(COMPONENT_TARGETS)
	gprbuild $(BUILD_OPTS) -P$(COMPONENT) -Xstacksize=$(COMPONENT_STACK_SIZE)
	$(MUCHECKSTACK) -P$(COMPONENT) -l$(COMPONENT_STACK_SIZE)
