cspecs: $(GEN_DIR)/.cspecs
$(GEN_DIR)/.cspecs: $(MUCGENSPEC) $(GENERATE_CSPECS_FROM) $(CSPEC_TARGETS)
	$(MUCGENSPEC) -i $(GENERATE_CSPECS_FROM) -o $(GEN_DIR)/$(COMPONENT).xml -I $(GEN_DIR) $(GEN_DIR)
	@touch $@
