--  This file is built automatically from data found on the
--  unicode web site (http://www.unicode.org)

package Unicode.Names.Number_Forms is
   Vulgar_Fraction_One_Third               : constant Unicode_Char := 16#2153#;
   Vulgar_Fraction_Two_Thirds              : constant Unicode_Char := 16#2154#;
   Vulgar_Fraction_One_Fifth               : constant Unicode_Char := 16#2155#;
   Vulgar_Fraction_Two_Fifths              : constant Unicode_Char := 16#2156#;
   Vulgar_Fraction_Three_Fifths            : constant Unicode_Char := 16#2157#;
   Vulgar_Fraction_Four_Fifths             : constant Unicode_Char := 16#2158#;
   Vulgar_Fraction_One_Sixth               : constant Unicode_Char := 16#2159#;
   Vulgar_Fraction_Five_Sixths             : constant Unicode_Char := 16#215A#;
   Vulgar_Fraction_One_Eighth              : constant Unicode_Char := 16#215B#;
   Vulgar_Fraction_Three_Eighths           : constant Unicode_Char := 16#215C#;
   Vulgar_Fraction_Five_Eighths            : constant Unicode_Char := 16#215D#;
   Vulgar_Fraction_Seven_Eighths           : constant Unicode_Char := 16#215E#;
   Fraction_Numerator_One                  : constant Unicode_Char := 16#215F#;
   Roman_Numeral_One                       : constant Unicode_Char := 16#2160#;
   Roman_Numeral_Two                       : constant Unicode_Char := 16#2161#;
   Roman_Numeral_Three                     : constant Unicode_Char := 16#2162#;
   Roman_Numeral_Four                      : constant Unicode_Char := 16#2163#;
   Roman_Numeral_Five                      : constant Unicode_Char := 16#2164#;
   Roman_Numeral_Six                       : constant Unicode_Char := 16#2165#;
   Roman_Numeral_Seven                     : constant Unicode_Char := 16#2166#;
   Roman_Numeral_Eight                     : constant Unicode_Char := 16#2167#;
   Roman_Numeral_Nine                      : constant Unicode_Char := 16#2168#;
   Roman_Numeral_Ten                       : constant Unicode_Char := 16#2169#;
   Roman_Numeral_Eleven                    : constant Unicode_Char := 16#216A#;
   Roman_Numeral_Twelve                    : constant Unicode_Char := 16#216B#;
   Roman_Numeral_Fifty                     : constant Unicode_Char := 16#216C#;
   Roman_Numeral_One_Hundred               : constant Unicode_Char := 16#216D#;
   Roman_Numeral_Five_Hundred              : constant Unicode_Char := 16#216E#;
   Roman_Numeral_One_Thousand              : constant Unicode_Char := 16#216F#;
   Small_Roman_Numeral_One                 : constant Unicode_Char := 16#2170#;
   Small_Roman_Numeral_Two                 : constant Unicode_Char := 16#2171#;
   Small_Roman_Numeral_Three               : constant Unicode_Char := 16#2172#;
   Small_Roman_Numeral_Four                : constant Unicode_Char := 16#2173#;
   Small_Roman_Numeral_Five                : constant Unicode_Char := 16#2174#;
   Small_Roman_Numeral_Six                 : constant Unicode_Char := 16#2175#;
   Small_Roman_Numeral_Seven               : constant Unicode_Char := 16#2176#;
   Small_Roman_Numeral_Eight               : constant Unicode_Char := 16#2177#;
   Small_Roman_Numeral_Nine                : constant Unicode_Char := 16#2178#;
   Small_Roman_Numeral_Ten                 : constant Unicode_Char := 16#2179#;
   Small_Roman_Numeral_Eleven              : constant Unicode_Char := 16#217A#;
   Small_Roman_Numeral_Twelve              : constant Unicode_Char := 16#217B#;
   Small_Roman_Numeral_Fifty               : constant Unicode_Char := 16#217C#;
   Small_Roman_Numeral_One_Hundred         : constant Unicode_Char := 16#217D#;
   Small_Roman_Numeral_Five_Hundred        : constant Unicode_Char := 16#217E#;
   Small_Roman_Numeral_One_Thousand        : constant Unicode_Char := 16#217F#;
   Roman_Numeral_One_Thousand_C_D          : constant Unicode_Char := 16#2180#;
   Roman_Numeral_Five_Thousand             : constant Unicode_Char := 16#2181#;
   Roman_Numeral_Ten_Thousand              : constant Unicode_Char := 16#2182#;
   Roman_Numeral_Reversed_One_Hundred      : constant Unicode_Char := 16#2183#;
end Unicode.Names.Number_Forms;
