# Muen Development Environment
#
# Prerequisites for nested emulation:
#   - Linux kernel >= 5.2.0 with CR3 fix:
#     https://patchwork.kernel.org/patch/11165185/
#
# Build container:
#   docker build -t muen-dev-env -f Dockerfile.muen-dev-env .
#
# Enter the container:
#   ./run.muen-dev-env muen-dev-env

# Base image
ARG distro_name=debian
ARG distro_version=bullseye
FROM ${distro_name}:${distro_version}

LABEL maintainer "Adrian-Ken Rueegsegger <ken@codelabs.ch>"
LABEL description "This image provides the build environment for the Muen project"

# Required packages
ARG packages="acpica-tools amtterm autoconf automake autopoint bc bison bzip2 \
ca-certificates ccache cpio curl file flex git-core gnupg inotify-tools \
iputils-ping kmod lcov libc6-dev libcurl4-gnutls-dev libelf-dev \
libfreetype6-dev libgmp10-dev libiberty-dev libncurses-dev libseccomp-dev \
libssl-dev libxml2-utils lighttpd make mtools openssh-client patch picocom \
pkg-config python3-minimal python3-lxml python3-colorlog python3-setuptools \
python3-pip qemu-system-x86 rsync screen tidy unzip vim wget xfonts-unifont \
xorriso xsltproc xz-utils zlib1g-dev"

# Build-time only. Will not appear on the muen.sk website
# Required to compile amtc/solo5
ARG build_packages="gcc"

# Additional, not strictly required packages. Will not appear on the muen.sk
# website
ARG packages="$packages $build_packages php7.4-cli php7.4-curl php7.4-xml"

# Add PHP PPA on Ubuntu distros, required for arcanist
ARG distro_name
ARG ubuntupkgs="gpg-agent software-properties-common"
RUN if [ "$distro_name" = "ubuntu" ]; then \
	apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --no-install-recommends $ubuntupkgs \
	&& add-apt-repository ppa:ondrej/php \
	&& apt purge -y --auto-remove $ubuntupkgs \
	&& rm -rf /var/lib/apt/lists/*; \
	fi

# Install dependencies
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -qq -y \
	--no-install-recommends \
	$packages \
	&& rm -rf /var/lib/apt/lists/*

# Alire
RUN wget --no-verbose https://github.com/alire-project/alire/releases/download/v1.2.1/alr-1.2.1-bin-x86_64-linux.zip -P /tmp/alr \
	&& (cd /tmp/alr && unzip alr-1.2.1-bin-x86_64-linux.zip && cp bin/alr /usr/local/bin) \
	&& rm -rf /tmp/alr

# amtc tool
RUN git clone https://github.com/schnoddelbotz/amtc.git /tmp/amtc \
	&& cd /tmp/amtc \
	&& make -j`nproc` amtc \
	&& cp src/amtc /usr/local/bin \
	&& rm -rf /tmp/amtc

# Install solo5. test_hello.muen is required by Github Actions CI.
RUN curl -sSL "https://github.com/Solo5/solo5/releases/download/v0.6.5/solo5-v0.6.5.tar.gz" -o /opt/solo5-v0.6.5.tar.gz \
	&& tar -C /opt -zxf /opt/solo5-v0.6.5.tar.gz \
	&& cd /opt/solo5-v0.6.5 \
	&& ./configure.sh \
	&& make -j`nproc`\
	&& make install-tools \
	&& rm /opt/solo5-v0.6.5.tar.gz

# Phabricator's arcanist for review workflow
RUN git clone https://github.com/codelabs-ch/arcanist.git /opt/arcanist

# Python modules
RUN pip3 install wheel \
	&& pip3 install 'lief==0.11.5' \
	&& pip3 install rangehttpserver

# Purge build-time packages
RUN apt-get --purge autoremove -y $build_packages

# Setup environment
ENV HOME /home/user
ENV LANG C.UTF-8
ENV PATH /opt/arcanist/bin:$PATH

RUN useradd --create-home --home-dir $HOME user -G dialout \
	&& chmod 755 /home/user

# Alire 'meta' crate for the Muen toolchain
ARG dev_env_rev=e106a56c8a8ebbb9b22172ac08461ed89a937ac8
RUN git clone https://git.codelabs.ch/alire/muen-dev-env.git $HOME/dev-env.alr \
	&& cd $HOME/dev-env.alr \
	&& git reset --hard $dev_env_rev \
	&& make

ADD bashrc $HOME/.bashrc
WORKDIR $HOME
USER user

CMD [ "bash" ]
