#!/bin/bash

set -ex
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $SCRIPTDIR/func.sh
cd $SCRIPTDIR

date_print "*** Starting '$0'"

lspci

ifconfig eth0 down
ifconfig br0 down

ifconfig eth1 up
ifconfig eth1 192.168.254.55
ping -c 3 192.168.254.1
ifconfig eth1 down

ifconfig br0 up
ifconfig eth0 up

./muenblock-test

date_print "*** '$0' DONE"

# run common integration tests
./integtest

./muenfs-poll-test

# trigger system panic to exercise crash audit
mount -t muenevents none /muenevents
screen -dm bash -c "sleep 2 && echo 1 > /muenevents/panic"
