#!/bin/bash

set -ex

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PEER=192.168.10.4

. $SCRIPTDIR/func.sh
cd "$SCRIPTDIR"

date_print "*** Starting '$0'"

cat /proc/cpuinfo

# cpu benchmark
sysbench --test=cpu --cpu-max-prime=10000 run

ping -c 3 $PEER
cat /sys/kernel/debug/muennet/net0/info
OPERSTATE=$(cat /sys/class/net/net0/operstate)
echo "net0: operstate $OPERSTATE"

./muennet-child-test

muenfs-marker /muenfs/virtual_keyboard
muenfs-test /muenfs/testchannel_1
muenfs-test /muenfs/testchannel_2

./muenevents-test

ifconfig
ethtool eth0

pingpong

iperf -c $PEER -fm

echo "Current date $(date -u +%Y%m%d)"

date_print "*** $0 DONE"
