#!/bin/bash

set -ex

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $SCRIPTDIR/func.sh
cd $SCRIPTDIR

SSH="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no lnx2"
MOUNTDIR="/muenevents"

$SSH modprobe muenevents
$SSH mkdir -p $MOUNTDIR
$SSH mount -t muenevents none $MOUNTDIR
$SSH muenfs-example /muenfs/example_request \
	/muenfs/example_response \
	/muenevents/example_request
$SSH umount $MOUNTDIR
