#!/bin/bash

MOUNTDIR="/muenevents"

modprobe muenevents
mkdir -p $MOUNTDIR
mount -t muenevents none $MOUNTDIR

taskset 0x1 find $MOUNTDIR -type f -exec echo -n {}" " \; -exec cat {} \;

umount $MOUNTDIR
