#!/bin/bash

set -ex
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. $SCRIPTDIR/func.sh

SHACMD="sha256sum -c sha256sum"
CRYPTDEV=/dev/muendiska5

echo 123 | cryptsetup luksOpen $CRYPTDEV crypt
pvscan
vgscan
vgchange -a y vg1
vgscan --mknodes
lvscan

mount /dev/vg1/testlv /mnt/2
cp -vR /mnt/1/files /mnt/2
cd /mnt/2/files
$SHACMD
rm -r /mnt/2/files
cd /
umount /mnt/2
fsck -y /dev/vg1/testlv
vgchange -a n vg1
cryptsetup luksClose crypt
