#!/bin/bash

# This script expects a block device on the server side with the following
# configuration:

# sdX1 - ext* partition - ref files
#  $ sudo mkfs.ext4 /dev/sdX1
#  $ sudo mount /dev/sdX1 /mnt
#  $ sudo mkdir /mnt/files && cd /mnt/files
#  $ sudo tools/scripts/integ/target_scripts/muenblock-ref .
# sdX2 - ext* partition
#  $ sudo mkfs.ext2 /dev/sdX2
# sdX5 - ext* on lvm on dm-crypt
#  $ sudo cryptsetup luksFormat /dev/sdX5
#  $ sudo cryptsetup luksOpen /dev/sdX5 test-crypt
#  $ sudo pvcreate /dev/mapper/test-crypt
#  $ sudo vgcreate vg1 /dev/mapper/test-crypt
#  $ sudo lvcreate -n testlv -L10G vg1
#  $ sudo mkfs.ext3 /dev/mapper/vg1-testlv
#  $ sudo vgchange -a n vg1
#  $ sudo cryptsetup luksClose test-crypt

set -ex
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. $SCRIPTDIR/func.sh
cd $SCRIPTDIR

REFS="/mnt/1/files"
SHACMD="sha256sum -c sha256sum"
SSH="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no lnx2"

perform_tests() {
	pushd $REFS
	$SHACMD

	rm -rf /mnt/1/files2
	cp -Rv $REFS /mnt/1/files2
	cd /mnt/1/files2
	$SHACMD
	rm -r /mnt/1/files2

	rm -rf /mnt/2/files
	cp -Rv $REFS /mnt/2/
	cd /mnt/2/files
	$SHACMD
	rm -r /mnt/2/files
	popd
	sync
}

test_title() {
	echo
	echo "****** $1"
	echo
}

test_title "lnx1 -> lnx2 XHCI"

$SSH target_scripts/muenblock-server

mkdir -p /mnt/1
mkdir -p /mnt/2

./muenblock-client
sleep 2
mount /dev/muendiska /mnt/1
mount /dev/muendiskb /mnt/2

perform_tests
umount /mnt/1
umount /mnt/2
fsck -n /dev/muendiska
fsck -n /dev/muendiskb
rmmod muenblock_client

test_title "lnx1 -> lnx2 XHCI [no server restart]"

./muenblock-client
sleep 2
mount /dev/muendiska /mnt/1
mount /dev/muendiskb /mnt/2

perform_tests
umount /mnt/1
umount /mnt/2
fsck -n /dev/muendiska
fsck -n /dev/muendiskb
rmmod muenblock_client

$SSH rmmod muenblock_server

test_title "lnx1 -> lnx2 XHCI [complete blockdev]"

sleep 2
$SSH target_scripts/muenblock-server-all
./muenblock-client
sleep 2

mount /dev/muendiska1 /mnt/1
mount /dev/muendiska2 /mnt/2

perform_tests
umount /mnt/2

test_title "lnx1 -> lnx2 XHCI [ext/LVM/crypt]"

./muenblock-lvops
umount /mnt/1
fsck -n /dev/muendiska1
fsck -n /dev/muendiska2

rmmod muenblock_client
$SSH rmmod muenblock_server

test_title "lnx1 -> ahci_drv AHCI"

./muenblock-client-native
sleep 2
mount /dev/muendiska1 /mnt/1
mount /dev/muendiska2 /mnt/2

perform_tests
umount /mnt/2

test_title "lnx1 -> ahci_drv AHCI [ext/LVM/crypt]"

./muenblock-lvops
umount /mnt/1
fsck -n /dev/muendiska1
fsck -n /dev/muendiska2

rmmod muenblock_client

echo "MUENBLOCKINTEGPASSED"
