#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. $SCRIPTDIR/func.sh
CHROOT=/mnt/1/stretch-chroot

execute "mount -o bind /dev $CHROOT/dev"
execute "mount -t sysfs sysfs $CHROOT/sys"
execute "mount -t proc proc $CHROOT/proc"

execute "chroot $CHROOT /bin/bash"

execute "umount $CHROOT/dev"
execute "umount $CHROOT/sys"
execute "umount $CHROOT/proc"
