#!/bin/bash

BLKDEV=sdc

echo none > /sys/class/block/${BLKDEV}/queue/scheduler

modprobe muenblock-server \
	req_shm_name=blockdev_request1 \
	resp_shm_name=blockdev_response1 \
	req_shm_protocol=9570208dca77db19 \
	resp_shm_protocol=9851be3282fef0dc \
	device_name=/dev/${BLKDEV} \
	poll_interval=1
