#!/bin/bash

modprobe muenblock-client \
   req_shm_name=blockdev_request1 \
   resp_shm_name=blockdev_response1 \
   req_shm_protocol=9570208dca77db19 \
   resp_shm_protocol=9851be3282fef0dc \
   poll_interval=1
