#!/bin/bash

set -ex

SSH="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no lnx2"

$SSH target_scripts/muennet-child-setup net0 child1 24 192.168.10.14
./muennet-child-setup net0 child1 24 192.168.10.13
ping -c 3 -I child1 192.168.10.14
cat /sys/kernel/debug/muennet/child1/info
muennet_cfg del_mark child1 24
muennet_cfg del_child child1
